export const GET_HOMEWORK_BY_CREATED_TEACHER_LOADING = 'GET_HOMEWORK_BY_CREATED_TEACHER_LOADING';
export const GET_HOMEWORK_BY_CREATED_TEACHER_SUCCESS = 'GET_HOMEWORK_BY_CREATED_TEACHER_SUCCESS';
export const GET_HOMEWORK_BY_CREATED_TEACHER_UNSUCCESS = 'GET_HOMEWORK_BY_CREATED_TEACHER_UNSUCCESS';

export const CREATE_NEW_HOMEWORK_LOADING = 'CREATE_NEW_HOMEWORK_LOADING';
export const CREATE_NEW_HOMEWORK_SUCCESS = 'CREATE_NEW_HOMEWORK_SUCCESS';
export const CREATE_NEW_HOMEWORK_UNSUCCESS = 'CREATE_NEW_HOMEWORK_UNSUCCESS';

export const DELETE_HOMEWORK_LOADING = 'DELETE_HOMEWORK_LOADING';
export const DELETE_HOMEWORK_SUCCESS = 'DELETE_HOMEWORK_SUCCESS';
export const DELETE_HOMEWORK_UNSUCCESS = 'DELETE_HOMEWORK_UNSUCCESS';

export const UPDATE_HOMEWORK_LOADING = 'UPDATE_HOMEWORK_LOADING';
export const UPDATE_HOMEWORK_SUCCESS = 'UPDATE_HOMEWORK_SUCCESS';
export const UPDATE_HOMEWORK_UNSUCCESS = 'UPDATE_HOMEWORK_UNSUCCESS';