export const GET_HOMEWORK_BY_CREATED_TEACHER_LOADING = 'GET_HOMEWORK_BY_CREATED_TEACHER_LOADING';
export const GET_HOMEWORK_BY_CREATED_TEACHER_SUCCESS = 'GET_HOMEWORK_BY_CREATED_TEACHER_SUCCESS';
export const GET_HOMEWORK_BY_CREATED_TEACHER_UNSUCCESS = 'GET_HOMEWORK_BY_CREATED_TEACHER_UNSUCCESS';

export const CREATE_NEW_HOMEWORK_LOADING = 'CREATE_NEW_HOMEWORK_LOADING';
export const CREATE_NEW_HOMEWORK_SUCCESS = 'CREATE_NEW_HOMEWORK_SUCCESS';
export const CREATE_NEW_HOMEWORK_UNSUCCESS = 'CREATE_NEW_HOMEWORK_UNSUCCESS';