export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGIN_REQUEST_LOADING = 'LOGIN_REQUEST_LOADING';
export const AUTHENTICATION_REFRESH = 'AUTHENTICATION_REFRESH';